# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisGui_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_jarvisGui(object):
    def setupUi(self, jarvisGui):
        jarvisGui.setObjectName("jarvisGui")
        jarvisGui.resize(1251, 771)
        self.centralwidget = QtWidgets.QWidget(jarvisGui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1251, 771))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../jarvis/jarvis_1.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(820, 660, 200, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(1020, 660, 200, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 0, 0);")

        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 451, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../jarvis/jarvis_2.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(600, 10, 300, 70))
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"font: Times New Roman;\n"
"font: Sitka small;\n"
"font-family: 'Beau Rivage', cursive;\n"
"color: yellow;\n"
"border-radius:none;\n"
"font-size:40px;")

        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(900, 10, 300, 70))
        self.textBrowser_2.setStyleSheet("background-color: transparent;\n"
"font: Times New Roman;\n"
"color: yellow;\n"
"border-radius:none;\n"
"font-size:40px;")

        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 350, 401, 321))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../jarvis/jarvis_3.gif"))
        self.label_3.setObjectName("label_3")
        jarvisGui.setCentralWidget(self.centralwidget)
        self.retranslateUi(jarvisGui)
        QtCore.QMetaObject.connectSlotsByName(jarvisGui)

    def retranslateUi(self, jarvisGui):
        _translate = QtCore.QCoreApplication.translate
        jarvisGui.setWindowTitle(_translate("jarvisGui", "MainWindow"))
        self.pushButton.setText(_translate("jarvisGui", "Run"))
        self.pushButton_2.setText(_translate("jarvisGui", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisGui = QtWidgets.QMainWindow()
    ui = Ui_jarvisGui()
    ui.setupUi(jarvisGui)
    jarvisGui.show()
    sys.exit(app.exec_())
